### ISSUE TITLE
Targeted variables are not recognized as variable_field

### ISSUE THREAD

**Issue by malashin** [tboby/cwtools-hoi4-config#10]
Numbers or variables work fine, target variables with `@` character in them don't.
```ruby
num_units_on_climate@cold_climate
avg_units_acclimation@cold_climate
```

![cwtools_targeted_variables](https://user-images.githubusercontent.com/13807986/51189345-93795000-192b-11e9-96d7-8323718a2e2d.png)

```ruby
### Compares a variable to a number or variable
## scope = any
alias[trigger:check_variable] = {
	variable_field = variable_field
}
### Compares a variable to a number or variable
## scope = any
alias[trigger:check_variable] = {
	var = value[variable]
	value = variable_field
	compare = less_than
	compare = less_than_or_equals
	compare = greater_than
	compare = greater_than_or_equals
	compare = equals
	compare = not_equals
}
```

**Comment by tboby** [comment]
Yeah, looks like a bug in `variable_field` checking.

![image](https://user-images.githubusercontent.com/447391/51246975-a750a080-1983-11e9-913b-c159cdeda133.png)
Works

![image](https://user-images.githubusercontent.com/447391/51246993-b59ebc80-1983-11e9-939f-594a772b67dd.png)
Doesn't.

I'll look into it.

**Comment by tboby** [comment]
This should now be resolved (although perhaps a few bugs to iron out)
