### ISSUE TITLE
False positive `Too many lv Field of Enum module_categories, expecting at most 1` - CW242

### ISSUE THREAD

**Issue by PPsyrius** [tboby/cwtools-hoi4-config#193]
Vanilla HoI4 has since allowed more than one field usage here:

False Positive Error example:
![image](https://github.com/cwtools/cwtools/assets/19505219/fb749724-467a-4de0-9048-ad9d3296f3a1)

Actual HoI4 code:
![image](https://github.com/cwtools/cwtools/assets/19505219/47bfac90-127b-4035-819f-6e398ec4c3c5)

**Comment by Pelmen323** [comment]
Done in https://github.com/Kaiserreich/cwtools-hoi4-config/commit/8aed02749be1177551ae830e4a688d63d17644c2
