### ISSUE TITLE
check_variable short syntax

### ISSUE THREAD

**Issue by malashin** [tboby/cwtools-hoi4-config#4]
`check_variable` has as short syntax form:
```ruby
check_variable = { var_name = var_name_2 }
check_variable = { var_name < var_name_2 }
check_variable = { var_name > var_name_2 }
```
https://hoi4.paradoxwikis.com/Variables#check_variable

Apart from long syntax, only `=` is implemented in the library at the moment, `<` and `>` are missing.

https://github.com/tboby/cwtools-hoi4-config/blob/f553300af895ef8a9f80f924218e0b6dc72eba2d/Config/triggers.cwt#L93-L109

**Comment by CaesarVincens** [comment]
Cwtools automatically converts < and > into = for the validator, that is, < and > are included for any check. There are some other issues with variables currently that may come up though. I've noticed that check_variable seems particularly buggy among the variable effects and triggers.

**Comment by malashin** [comment]
I use VS Code extension and get this error. If `>` and `<` are replaced with `=` it works fine, otherwise it defaults to the long syntax and is looking for `var = varname`.

![cwtools_check_variable](https://user-images.githubusercontent.com/13807986/51082110-34111980-174c-11e9-8c1e-0902a2be9aba.png)

**Comment by CaesarVincens** [comment]
Ah, good catch then, that's likely the same errors I've been seeing. I've just not checked using an equals sign. I've tagged tboby to check it out.

**Comment by tboby** [comment]
That's really weird, the parser should treat them exactly the same. I'll have a look and see what's going on.
I've merged some changes to the variable rules to master, which may (or may not) make a difference, so try it with those.

**Comment by malashin** [comment]
This was fixed after the last dev branch merge.
