### ISSUE TITLE
Create leader effects picture path

### ISSUE THREAD

**Issue by malashin** [tboby/cwtools-hoi4-config#8]
Talking about HOI4 here, there might be something similar in other PDX titles.

There is quite an oddity with the way PDX made picture assignment for leaders.
You can either use gfx files name that is located in current countries leaders folder or use full path to that file.

Let's say the countries tag is `BRK`. Both of this cases will work fine for `create_country_leader`:
```ruby
create_country_leader = {
	picture = "Portrait_BRK_Graven.dds"
}

create_country_leader = {
	picture = "gfx/leaders/BRK/Portrait_BRK_Graven.dds"
}
```

`create_field_marshal`, `create_corps_commander`, `create_navy_leader` on the other hand won't accept the full path as `picture`. Unlike `create_country_leader `, those three use another field to get the full path `portrait_path`.

```ruby
# works fine
create_field_marshal = {
	picture = "Portrait_BRK_Graven.dds"
}

# won't find the picture, no errors in the error log
create_field_marshal = {
	picture = "gfx/leaders/BRK/Portrait_BRK_Graven.dds"
}

# works fine
create_field_marshal = {
	portrait_path = "gfx/leaders/BRK/Portrait_BRK_Graven.dds"
}
```

Right now `portrait_path` is not recognized by the parser: `Unexpected node portrait_path in create_corps_commander`. So it should be added to those three effects and those three only, `create_country_leader` will return an error on game startup if it is used in there.

Ideally there should be either `portrait_path` or `picture` in those effects, not both of them at the same time.

**Comment by tboby** [comment]
> You can either use gfx files name that is located in current countries leaders folder
Is it actually restricted to the current country's folder?
E.g., would it still find `gfx/leaders/BLAHBLAH/Portrait_BRK_Graven.dds`?

We don't quite have a rule for file names without a specific folder. I'll think on that one a bit more.

`portrait_path = filepath` should handle the full filepath.

>Ideally there should be either portrait_path or picture in those effects, not both of them at the same time.
There's no easy way of doing "one and not the other" right now. It doesn't come up very often, and I'm worried it'll make things a bit complicated.

**Comment by malashin** [comment]
> Is it actually restricted to the current country's folder?
E.g., would it still find gfx/leaders/BLAHBLAH/Portrait_BRK_Graven.dds?

If full path provided is it will work with any folder. Current countries folder is used if filename is passed without path, as in `Portrait_BRK_Graven.dds`, instead of `/gfx/leaders/BRK/Portrait_BRK_Graven.dds`.
